/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_07;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.System.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import pertemuan_07.DbUtils;
/**
 *
 * @author IT GRC
 */
public class simulasi_06 extends javax.swing.JFrame {
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/SIMULASI_UTS";
    String user = "postgres";
    String password = "123";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    /**
     * Creates new form simulasi_06
     */
    public simulasi_06() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfISBN = new javax.swing.JTextField();
        tfJudul = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        tfPenerbit = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ENTITAS BUKU");

        jLabel2.setText("ISBN");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Tahun Terbit");

        jLabel5.setText("Penerbit");

        tfISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfISBNActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tbTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(tfTahun, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPenerbit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnInsert)
                                .addGap(69, 69, 69)
                                .addComponent(btnUpdate)
                                .addGap(58, 58, 58)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear))
                            .addComponent(tfISBN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfISBNActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String ISBN, judul_buku, tahun_terbit, penerbit;
        String hehe = tfISBN.getText();
        String hoho = tfJudul.getText();
        String huhu = tfTahun.getText();
        String hihi = tfPenerbit.getText();

        if (hehe.trim().isEmpty() && hoho.trim().isEmpty() && huhu.trim().isEmpty() && hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi dulu yaa data bukunya! ");
        } else if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi ISBN dulu yaa! ");
        } else if (hoho.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Judul Buku anda dulu!");
        } else if (huhu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Tahun Terbit dulu!");
        } else if (hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Penerbit dulu!");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
                conn.setAutoCommit(false);

                String sql = "INSERT INTO buku VALUES(?,?,?,?)";
                pstmt = conn.prepareStatement(sql);

                ISBN = tfISBN.getText();
                judul_buku = tfJudul.getText();
                tahun_terbit = tfTahun.getText();
                penerbit = tfPenerbit.getText();

                pstmt.setString(1, ISBN);
                pstmt.setString(2, judul_buku);
                pstmt.setLong(3, Long.parseLong(tahun_terbit));
                pstmt.setString(4, penerbit);
               
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "data berhasil ditambahkan");
                conn.commit();// Commit transaksi setelah sejumlah operasi-insert berhasil
                pstmt.close();
                conn.close();

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "terjadi kesalahan saat pengisian");
            }
        }
        bersih();
        tampil();                                        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String ISBN,  judulBukuBaru, tahunTerbitBaru, penerbitBaru;
        String hehe = tfISBN.getText();
        String hoho = tfJudul.getText();
        String huhu = tfTahun.getText();
        String hihi = tfPenerbit.getText();

        if (hehe.trim().isEmpty() && hoho.trim().isEmpty() && huhu.trim().isEmpty() && hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan dulu data buku yang ingin diupdate! ");
        } else if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi ISBN dulu yaa! ");
        } else if (hoho.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Judul Buku dulu yang ingin diupdate!");
        } else if (huhu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Tahun Terbit dulu yang ingin diupdate!");
        } else if (hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Penerbit dulu yang ingin diupdate!");
        } else {
            try {
                Class.forName(driver);
                String sql = "UPDATE buku SET judul_buku = ?, tahun_terbit = ?, penerbit = ? WHERE ISBN = ?";
                conn = DriverManager.getConnection(koneksi, user, password);
                pstmt = conn.prepareStatement(sql);

                ISBN = tfISBN.getText();
                judulBukuBaru = tfJudul.getText();
                tahunTerbitBaru = tfTahun.getText();
                penerbitBaru = tfPenerbit.getText();

                pstmt.setString(1, judulBukuBaru);
                pstmt.setLong(2, Long.parseLong(tahunTerbitBaru));
                pstmt.setString(3, penerbitBaru);               
                pstmt.setString(4, ISBN);
                
                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "data berhasil diupdate!");
                    pstmt.close();
                    conn.close();
                    bersih();
                } else {
                    JOptionPane.showMessageDialog(null, "data tidak ditemukan");
                }
            } catch (ClassNotFoundException | SQLException ex) {
            }
            tampil();
        }   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String ISBN;
        String hehe = tfISBN.getText();

        if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan dulu data buku yang ingin dihapus!");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);

                int jawab = JOptionPane.showConfirmDialog(null, "Silakan Konfirmasi?");
                switch (jawab) {
                    case JOptionPane.YES_OPTION:
                        String sql = "DELETE FROM buku WHERE ISBN = ?";
                        pstmt = conn.prepareStatement(sql);

                        ISBN = tfISBN.getText();
                        pstmt.setString(1, ISBN);
                        pstmt.executeUpdate();

                        pstmt.close();
                        conn.close();
                        bersih();
                        break;

                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(this, "anda menjawab tidak");
                        break;
                }

            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("terjadi kesalahan saat melakukan operasi insert dalam loop.");
                ex.printStackTrace();
                try {
                    if (conn != null) {
                        conn.rollback();
                    }
                } catch (SQLException e) {
                    System.out.println("Gagal melakukan rollback transaksi.");
                    e.printStackTrace();
                }
            }
            tampil();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelMouseClicked
      int row = tbTabel.getSelectedRow();
        tfISBN.setText(tbTabel.getValueAt(row, 0).toString());
        tfJudul.setText(tbTabel.getValueAt(row, 1).toString());
        tfTahun.setText(tbTabel.getValueAt(row, 2).toString());
        tfPenerbit.setText(tbTabel.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbTabelMouseClicked
   
    
    
    public void tampil() {
        try {
            // TODO code application logi
            Class.forName(driver);
            String sql = "SELECT * FROM buku ";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            while (!conn.isClosed()) {

                ResultSet rs = stmt.executeQuery(sql);
                this.tbTabel.setModel(DbUtils.resultSetToTableModel(rs));
                while (rs.next()) {
                    System.out.println(String.valueOf(rs.getObject(1)) + " " + String.valueOf(rs.getObject(2)) + " " + String.valueOf(rs.getObject(3)) + " " + String.valueOf(rs.getObject(4)));
                }
                conn.close();
            }

            stmt.close();

        } catch (ClassNotFoundException | SQLException ex) {
             java.util.logging.Logger.getLogger(simulasi_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void bersih() {
        tfISBN.setText("");
        tfJudul.setText("");
        tfTahun.setText("");
        tfPenerbit.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulasi_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulasi_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulasi_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulasi_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simulasi_06().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabel;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
